name: Action workflow

on:
#  push:
#    branches:
#      - main
#      - "feature/*" # matches feature/featA, feature/featB. doesnot match feature/feat/A
#      - "feature/**" 
    #branches-ignore:
    # - dev
    #tags:
    #  - v1.*
    #paths:
    #  - "**.js"
    #  - abc/def/**

 # repository_dispatch:
 #   types: [build]
 # schedule:
 #  - cron: "0/5 * * * *"
 #  - cron: "0/8 * * * *"
 # push:
  pull_request:
    types: [closed, assigned, reopened, opened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of files on runner
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token}}"
      - name: Repo checkout
        uses: actions/checkout@v1
      - name: List of files on runner after checkout
        run: |
          pwd
          ls -a
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Smruti
      - name: Log greeting time
        run: echo "${{steps.greet.outputs.time}}"