name: Shell commands

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Smruti
      - name: Log greeting time
        run: echo "${{steps.greet.outputs.time}}"