name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # after 10 mins, github will kill the job
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        continue-on-error: true  # Even if the step fails, all other steps will run
        id: github_context_step
        run: eccho '${{ toJSON(github) }}'
      - name: Dump job context
        if: failure()  
        # This step runs even the previous job fails
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: always()  
        # Whatever happen to previous steps, this step should always run
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'