name: Shell commands

on:
#  push:
  workflow_dispatch:

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt a file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json secret.json.gpg
        env: 
          PASSPHRASE: ${{  secrets.PASSPHRASE }}
      - name: Print out file content
        run: cat $HOME/secret.json